Adding typer and click to requirements
Attempt to solve the pytest error when installing dependencies:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
typer 0.24.1 requires click>=8.2.1, but you have click 8.1.7 which is incompatible.